# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/ph2n/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/bin/DR_AP_Service:system/bin/DR_AP_Service \
	vendor/lge/ph2n/proprietary/bin/mm-audio-ftm:system/bin/mm-audio-ftm \
	vendor/lge/ph2n/proprietary/bin/qmi_simple_ril_test:system/bin/qmi_simple_ril_test \
	vendor/lge/ph2n/proprietary/bin/subsystem_ramdump:system/bin/subsystem_ramdump \
	vendor/lge/ph2n/proprietary/bin/tbaseLoader:system/bin/tbaseLoader \
	vendor/lge/ph2n/proprietary/bin/test_diag:system/bin/test_diag \
	vendor/lge/ph2n/proprietary/bin/testapp_diag_senddata:system/bin/testapp_diag_senddata \
	vendor/lge/ph2n/proprietary/bin/tbaseLoader:system/bin/tbaseLoader \
	vendor/lge/ph2n/proprietary/bin/wcnss_filter:system/bin/wcnss_filter \
	vendor/lge/ph2n/proprietary/bin/vendor_cmd_tool:system/bin/vendor_cmd_tool \
	vendor/lge/ph2n/proprietary/vendor/bin/mm-pp-dpps:system/vendor/bin/mm-pp-dpps \
	vendor/lge/ph2n/proprietary/vendor/bin/esepmdaemon:system/vendor/bin/esepmdaemon \

# Perfd
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/bin/msm_irqbalance:system/bin/msm_irqbalance \
	vendor/lge/ph2n/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
	vendor/lge/ph2n/proprietary/vendor/etc/perf-profile0.conf:system/vendor/etc/perf-profile0.conf \
	vendor/lge/ph2n/proprietary/vendor/etc/perf-profile1.conf:system/vendor/etc/perf-profile1.conf \
	vendor/lge/ph2n/proprietary/vendor/etc/msm_irqbalance.conf:system/vendor/etc/msm_irqbalance.conf \
	vendor/lge/ph2n/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so

# Chargerlogo
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_01.png:system/vendor/etc/chargerimages/battery_charging_01.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_02.png:system/vendor/etc/chargerimages/battery_charging_02.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_03.png:system/vendor/etc/chargerimages/battery_charging_03.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_04.png:system/vendor/etc/chargerimages/battery_charging_04.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_05.png:system/vendor/etc/chargerimages/battery_charging_05.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_06.png:system/vendor/etc/chargerimages/battery_charging_06.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_07.png:system/vendor/etc/chargerimages/battery_charging_07.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_08.png:system/vendor/etc/chargerimages/battery_charging_08.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_ani_01.png:system/vendor/etc/chargerimages/battery_charging_ani_01.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_ani_02.png:system/vendor/etc/chargerimages/battery_charging_ani_02.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_bg.png:system/vendor/etc/chargerimages/battery_charging_bg.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_complete.png:system/vendor/etc/chargerimages/battery_charging_complete.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_dummy.png:system/vendor/etc/chargerimages/battery_charging_dummy.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_insert.png:system/vendor/etc/chargerimages/battery_charging_insert.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_00.png:system/vendor/etc/chargerimages/battery_charging_warning_1_00.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_01.png:system/vendor/etc/chargerimages/battery_charging_warning_1_01.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_02.png:system/vendor/etc/chargerimages/battery_charging_warning_1_02.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_03.png:system/vendor/etc/chargerimages/battery_charging_warning_1_03.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_04.png:system/vendor/etc/chargerimages/battery_charging_warning_1_04.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_05.png:system/vendor/etc/chargerimages/battery_charging_warning_1_05.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_06.png:system/vendor/etc/chargerimages/battery_charging_warning_1_06.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_07.png:system/vendor/etc/chargerimages/battery_charging_warning_1_07.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_1_08.png:system/vendor/etc/chargerimages/battery_charging_warning_1_08.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning_blink.png:system/vendor/etc/chargerimages/battery_charging_warning_blink.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_charging_warning.png:system/vendor/etc/chargerimages/battery_charging_warning.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_invalid_01.png:system/vendor/etc/chargerimages/battery_invalid_01.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_invalid_02.png:system/vendor/etc/chargerimages/battery_invalid_02.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_0.png:system/vendor/etc/chargerimages/battery_percent_0.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_1.png:system/vendor/etc/chargerimages/battery_percent_1.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_2.png:system/vendor/etc/chargerimages/battery_percent_2.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_3.png:system/vendor/etc/chargerimages/battery_percent_3.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_4.png:system/vendor/etc/chargerimages/battery_percent_4.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_5.png:system/vendor/etc/chargerimages/battery_percent_5.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_6.png:system/vendor/etc/chargerimages/battery_percent_6.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_7.png:system/vendor/etc/chargerimages/battery_percent_7.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_8.png:system/vendor/etc/chargerimages/battery_percent_8.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent_9.png:system/vendor/etc/chargerimages/battery_percent_9.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/battery_percent.png:system/vendor/etc/chargerimages/battery_percent.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/black_bg.png:system/vendor/etc/chargerimages/black_bg.png \
	vendor/lge/ph2n/proprietary/vendor/etc/chargerimages/chargerlogo.ini:system/vendor/etc/chargerimages/chargerlogo.ini

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/vendor/lib/hw/sound_trigger.primary.msm8937.so:system/vendor/lib/hw/sound_trigger.primary.msm8937.so

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/ffu/FFUSKHYNIX_484147326505_0000000000000008.bin:root/ffu/FFUSKHYNIX_484147326505_0000000000000008.bin \
	vendor/lge/ph2n/proprietary/ffu/FFUSKHYNIX_484147326505_0000000000000008.bin:recovery/root/ffu/FFUSKHYNIX_484147326505_0000000000000008.bin

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/sbin/chargerlogo:root/sbin/chargerlogo \
	vendor/lge/ph2n/proprietary/sbin/lge_fota:root/sbin/lge_fota \
	vendor/lge/ph2n/proprietary/sbin/lge_fota_launcher:root/sbin/lge_fota_launcher \
	vendor/lge/ph2n/proprietary/sbin/lge_gota_launcher:root/sbin/lge_gota_launcher \
	vendor/lge/ph2n/proprietary/sbin/pub:root/sbin/pub \
	vendor/lge/ph2n/proprietary/sbin/sreadahead_check:root/sbin/sreadahead_check \
	vendor/lge/ph2n/proprietary/sbin/treadahead:root/sbin/treadahead \
	vendor/lge/ph2n/proprietary/sbin/wallpaper:root/sbin/wallpaper

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/sbin/sreadahead_check:recovery/root/sbin/sreadahead_check \
	vendor/lge/ph2n/proprietary/sbin/treadahead:recovery/root/sbin/treadahead


PRODUCT_COPY_FILES += \
 	vendor/lge/ph2n/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
 	vendor/lge/ph2n/proprietary/app/mcRegistry/08880000000000000000000000000000.tlbin:system/app/mcRegistry/08880000000000000000000000000000.tlbin

# Camera
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
	vendor/lge/ph2n/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	vendor/lge/ph2n/proprietary/lib/libarcsoft_beauty_shot.so:system/lib/libarcsoft_beauty_shot.so \
	vendor/lge/ph2n/proprietary/lib/libfilm_emulation.so:system/lib/libfilm_emulation.so \
	vendor/lge/ph2n/proprietary/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
	vendor/lge/ph2n/proprietary/lib/libNaturalEffect.so:system/lib/libNaturalEffect.so \
	vendor/lge/ph2n/proprietary/lib/libmm-qcamera.so:system/lib/libmm-qcamera.so \
	vendor/lge/ph2n/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
	vendor/lge/ph2n/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
	vendor/lge/ph2n/proprietary/lib/libmorpho_image_stab31.so:system/lib/libmorpho_image_stab31.so \
 	vendor/lge/ph2n/proprietary/lib/hw/camera.msm8937.so:system/lib/hw/camera.msm8937.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libactuator_dw9718.so:system/vendor/lib/libactuator_dw9718.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_a3_default_preview.so:system/vendor/lib/libchromatix_hi553_a3_default_preview.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_a3_default_video.so:system/vendor/lib/libchromatix_hi553_a3_default_video.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_a3_hfr_120.so:system/vendor/lib/libchromatix_hi553_a3_hfr_120.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_a3_hfr_60.so:system/vendor/lib/libchromatix_hi553_a3_hfr_60.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_a3_hfr_90.so:system/vendor/lib/libchromatix_hi553_a3_hfr_90.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_common.so:system/vendor/lib/libchromatix_hi553_common.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_ds_chromatix.so:system/vendor/lib/libchromatix_hi553_cpp_ds_chromatix.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_hfr_120.so:system/vendor/lib/libchromatix_hi553_cpp_hfr_120.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_hfr_60.so:system/vendor/lib/libchromatix_hi553_cpp_hfr_60.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_hfr_90.so:system/vendor/lib/libchromatix_hi553_cpp_hfr_90.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_liveshot.so:system/vendor/lib/libchromatix_hi553_cpp_liveshot.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_preview.so:system/vendor/lib/libchromatix_hi553_cpp_preview.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_snapshot.so:system/vendor/lib/libchromatix_hi553_cpp_snapshot.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_us_chromatix.so:system/vendor/lib/libchromatix_hi553_cpp_us_chromatix.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_video.so:system/vendor/lib/libchromatix_hi553_cpp_video.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_cpp_video_full.so:system/vendor/lib/libchromatix_hi553_cpp_video_full.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_default_video.so:system/vendor/lib/libchromatix_hi553_default_video.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_postproc.so:system/vendor/lib/libchromatix_hi553_postproc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_preview.so:system/vendor/lib/libchromatix_hi553_preview.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_snapshot.so:system/vendor/lib/libchromatix_hi553_snapshot.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_video_full.so:system/vendor/lib/libchromatix_hi553_video_full.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_zsl_preview.so:system/vendor/lib/libchromatix_hi553_zsl_preview.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_hi553_zsl_video.so:system/vendor/lib/libchromatix_hi553_zsl_video.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_common.so:system/vendor/lib/libchromatix_mn34153_common.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_ds_chromatix.so:system/vendor/lib/libchromatix_mn34153_cpp_ds_chromatix.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_hfr_120.so:system/vendor/lib/libchromatix_mn34153_cpp_hfr_120.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_hfr_60.so:system/vendor/lib/libchromatix_mn34153_cpp_hfr_60.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_hfr_90.so:system/vendor/lib/libchromatix_mn34153_cpp_hfr_90.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_liveshot.so:system/vendor/lib/libchromatix_mn34153_cpp_liveshot.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_preview.so:system/vendor/lib/libchromatix_mn34153_cpp_preview.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_snapshot.so:system/vendor/lib/libchromatix_mn34153_cpp_snapshot.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_us_chromatix.so:system/vendor/lib/libchromatix_mn34153_cpp_us_chromatix.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_video.so:system/vendor/lib/libchromatix_mn34153_cpp_video.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_cpp_video_full.so:system/vendor/lib/libchromatix_mn34153_cpp_video_full.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_default_preview_dw9718.so:system/vendor/lib/libchromatix_mn34153_default_preview_dw9718.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_default_video.so:system/vendor/lib/libchromatix_mn34153_default_video.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_default_video_dw9718.so:system/vendor/lib/libchromatix_mn34153_default_video_dw9718.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_hfr_120.so:system/vendor/lib/libchromatix_mn34153_hfr_120.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_hfr_120_dw9718.so:system/vendor/lib/libchromatix_mn34153_hfr_120_dw9718.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_hfr_60.so:system/vendor/lib/libchromatix_mn34153_hfr_60.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_hfr_60_dw9718.so:system/vendor/lib/libchromatix_mn34153_hfr_60_dw9718.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_hfr_90.so:system/vendor/lib/libchromatix_mn34153_hfr_90.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_hfr_90_dw9718.so:system/vendor/lib/libchromatix_mn34153_hfr_90_dw9718.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_liveshot.so:system/vendor/lib/libchromatix_mn34153_liveshot.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_postproc.so:system/vendor/lib/libchromatix_mn34153_postproc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_preview.so:system/vendor/lib/libchromatix_mn34153_preview.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_snapshot.so:system/vendor/lib/libchromatix_mn34153_snapshot.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_video_full.so:system/vendor/lib/libchromatix_mn34153_video_full.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_zsl_preview_dw9718.so:system/vendor/lib/libchromatix_mn34153_zsl_preview_dw9718.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromatix_mn34153_zsl_video_dw9718.so:system/vendor/lib/libchromatix_mn34153_zsl_video_dw9718.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_dcrf.so:system/vendor/lib/libmmcamera2_dcrf.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_mct.so:system/vendor/lib/libmmcamera2_mct.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so:system/vendor/lib/libmmcamera2_pp_buf_mgr.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_stats_algorithm_sensors.so:system/vendor/lib/libmmcamera2_stats_algorithm_sensors.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_at24c16d_eeprom.so:system/vendor/lib/libmmcamera_at24c16d_eeprom.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_chromaflash_lib.so:system/vendor/lib/libmmcamera_chromaflash_lib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_dbg.so:system/vendor/lib/libmmcamera_dbg.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_dcrf_lib.so:system/vendor/lib/libmmcamera_dcrf_lib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_dummyalgo.so:system/vendor/lib/libmmcamera_dummyalgo.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_eebinparse.so:system/vendor/lib/libmmcamera_eebinparse.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_eeprom_util.so:system/vendor/lib/libmmcamera_eeprom_util.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_eztune_module.so:system/vendor/lib/libmmcamera_eztune_module.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_hi553.so:system/vendor/lib/libmmcamera_hi553.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so:system/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_abf40.so:system/vendor/lib/libmmcamera_isp_abf40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_bcc40.so:system/vendor/lib/libmmcamera_isp_bcc40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_be_stats44.so:system/vendor/lib/libmmcamera_isp_be_stats44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_bf_stats47.so:system/vendor/lib/libmmcamera_isp_bf_stats47.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_bg_stats44.so:system/vendor/lib/libmmcamera_isp_bg_stats44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so:system/vendor/lib/libmmcamera_isp_bhist_stats44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_bpc40.so:system/vendor/lib/libmmcamera_isp_bpc40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so:system/vendor/lib/libmmcamera_isp_chroma_enhan40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so:system/vendor/lib/libmmcamera_isp_chroma_suppress40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so:system/vendor/lib/libmmcamera_isp_clamp_encoder40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so:system/vendor/lib/libmmcamera_isp_clamp_video40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so:system/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_color_correct40.so:system/vendor/lib/libmmcamera_isp_color_correct40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder40.so:system/vendor/lib/libmmcamera_isp_color_xform_encoder40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so:system/vendor/lib/libmmcamera_isp_color_xform_viewfinder40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_cs_stats44.so:system/vendor/lib/libmmcamera_isp_cs_stats44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_demosaic40.so:system/vendor/lib/libmmcamera_isp_demosaic40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_demux40.so:system/vendor/lib/libmmcamera_isp_demux40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_encoder40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so:system/vendor/lib/libmmcamera_isp_fovcrop_viewfinder40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_gamma40.so:system/vendor/lib/libmmcamera_isp_gamma40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_ihist_stats44.so:system/vendor/lib/libmmcamera_isp_ihist_stats44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_linearization40.so:system/vendor/lib/libmmcamera_isp_linearization40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_ltm44.so:system/vendor/lib/libmmcamera_isp_ltm44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so:system/vendor/lib/libmmcamera_isp_luma_adaptation40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_mce40.so:system/vendor/lib/libmmcamera_isp_mce40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff40.so:system/vendor/lib/libmmcamera_isp_mesh_rolloff40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_rs_stats44.so:system/vendor/lib/libmmcamera_isp_rs_stats44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder44.so:system/vendor/lib/libmmcamera_isp_scaler_encoder44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so:system/vendor/lib/libmmcamera_isp_scaler_viewfinder44.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_sce40.so:system/vendor/lib/libmmcamera_isp_sce40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_sub_module.so:system/vendor/lib/libmmcamera_isp_sub_module.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_template.so:system/vendor/lib/libmmcamera_isp_template.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_isp_wb40.so:system/vendor/lib/libmmcamera_isp_wb40.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_llvd.so:system/vendor/lib/libmmcamera_llvd.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_mn34153.so:system/vendor/lib/libmmcamera_mn34153.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_optizoom_lib.so:system/vendor/lib/libmmcamera_optizoom_lib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_ov8858.so:system/vendor/lib/libmmcamera_ov8858.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_ov8858_otp.so:system/vendor/lib/libmmcamera_ov8858_otp.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_ppbase_module.so:system/vendor/lib/libmmcamera_ppbase_module.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_s5k3p3.so:system/vendor/lib/libmmcamera_s5k3p3.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_stillmore_lib.so:system/vendor/lib/libmmcamera_stillmore_lib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_thread_services.so:system/vendor/lib/libmmcamera_thread_services.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_trueportrait_lib.so:system/vendor/lib/libmmcamera_trueportrait_lib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_tuning.so:system/vendor/lib/libmmcamera_tuning.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_tuning_lookup.so:system/vendor/lib/libmmcamera_tuning_lookup.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_ubifocus_lib.so:system/vendor/lib/libmmcamera_ubifocus_lib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmcamera_vpu_module.so:system/vendor/lib/libmmcamera_vpu_module.so

# Loggers
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/bin/check_data_mount.sh:system/bin/check_data_mount.sh \
	vendor/lge/ph2n/proprietary/bin/digicl.sh:system/bin/digicl.sh \
	vendor/lge/ph2n/proprietary/bin/diag_klog:system/bin/diag_klog \
	vendor/lge/ph2n/proprietary/bin/diag_mdlog:system/bin/diag_mdlog \
	vendor/lge/ph2n/proprietary/bin/diag_socket_log:system/bin/diag_socket_log \
	vendor/lge/ph2n/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
	vendor/lge/ph2n/proprietary/bin/kernel_logger:system/bin/kernel_logger \
	vendor/lge/ph2n/proprietary/bin/info2presslog.sh:system/bin/info2presslog.sh \
	vendor/lge/ph2n/proprietary/bin/logger_events.sh:system/bin/logger_events.sh \
	vendor/lge/ph2n/proprietary/bin/logger_kernel.sh:system/bin/logger_kernel.sh \
	vendor/lge/ph2n/proprietary/bin/logger_ims_packet.sh:system/bin/logger_ims_packet.sh \
	vendor/lge/ph2n/proprietary/bin/logger_main.sh:system/bin/logger_main.sh \
	vendor/lge/ph2n/proprietary/bin/logger_memory.sh:system/bin/logger_memory.sh \
	vendor/lge/ph2n/proprietary/bin/logger_packet.sh:system/bin/logger_packet.sh \
	vendor/lge/ph2n/proprietary/bin/logger_power.sh:system/bin/logger_power.sh \
	vendor/lge/ph2n/proprietary/bin/logger_radio.sh:system/bin/logger_radio.sh \
	vendor/lge/ph2n/proprietary/bin/logger_system.sh:system/bin/logger_system.sh \
	vendor/lge/ph2n/proprietary/bin/logger_setupwizard.sh:system/bin/logger_setupwizard.sh \
	vendor/lge/ph2n/proprietary/bin/logger_xfrm.sh:system/bin/logger_xfrm.sh \
	vendor/lge/ph2n/proprietary/bin/memory_logger:system/bin/memory_logger \
	vendor/lge/ph2n/proprietary/bin/modem_debug_info.sh:system/bin/modem_debug_info.sh \
	vendor/lge/ph2n/proprietary/bin/morningcall:system/bin/morningcall \
	vendor/lge/ph2n/proprietary/bin/power_logger:system/bin/power_logger \
	vendor/lge/ph2n/proprietary/bin/pktlogconf:system/bin/pktlogconf \
	vendor/lge/ph2n/proprietary/bin/presslog:system/bin/presslog \
	vendor/lge/ph2n/proprietary/bin/thermal_logging:system/bin/thermal_logging \
	vendor/lge/ph2n/proprietary/bin/WifiLogger_app:system/bin/WifiLogger_app

# GPS
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/bin/garden_app:system/bin/garden_app \
	vendor/lge/ph2n/proprietary/lib/libgps.utils.so:system/lib/utils.so \
	vendor/lge/ph2n/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
	vendor/lge/ph2n/proprietary/lib/libloc_ds_api.so:system/lib/libloc_ds_api.so \
	vendor/lge/ph2n/proprietary/lib/libloc_core.so:system/lib/libloc_core.so \
	vendor/lge/ph2n/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
	vendor/lge/ph2n/proprietary/lib/libloc_pla.so:system/lib/libloc_pla.so \
	vendor/lge/ph2n/proprietary/lib/libloc_stub.so:system/lib/libloc_stub.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblowi_wifihal.so:system/vendor/lib/liblowi_wifihal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblowi_wifihal_nl.so:system/vendor/lib/liblowi_wifihal_nl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libhwdaphal.so:system/vendor/lib/libhwdaphal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libconnctrl.so:system/vendor/lib/libconnctrl.so

# LG bin
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/bin/ipsecclient:system/bin/ipsecclient \
	vendor/lge/ph2n/proprietary/bin/ipsecstarter:system/bin/ipsecstarter \
	vendor/lge/ph2n/proprietary/bin/lg_dm_router:system/bin/lg_dm_router \
	vendor/lge/ph2n/proprietary/bin/lg_odm_service:system/bin/lg_odm_service \
	vendor/lge/ph2n/proprietary/bin/lgdrmserver:system/bin/lgdrmserver \
	vendor/lge/ph2n/proprietary/bin/lghashstorageserver:system/bin/lghashstorageserver \
	vendor/lge/ph2n/proprietary/bin/lgsecclkserver:system/bin/lgsecclkserver

# NFC
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/lib/libLGnfc_config.so:system/lib/libLGnfc_config.so \
	vendor/lge/ph2n/proprietary/lib/libLGnfc_jni.so:system/lib/libLGnfc_jni.so \
	vendor/lge/ph2n/proprietary/vendor/firmware/libpn548ad_fw.so:system/vendor/firmware/libpn548ad_fw.so

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/bin/adsprpcd:system/bin/adsprpcd \
	vendor/lge/ph2n/proprietary/bin/advanced_moca:system/bin/advanced_moca \
	vendor/lge/ph2n/proprietary/bin/atd:system/bin/atd \
	vendor/lge/ph2n/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
	vendor/lge/ph2n/proprietary/bin/athdiag:system/bin/athdiag \
	vendor/lge/ph2n/proprietary/bin/bdaddr_loader:system/bin/bdaddr_loader \
	vendor/lge/ph2n/proprietary/bin/btnvtool:system/bin/btnvtool \
	vendor/lge/ph2n/proprietary/bin/ccmd:system/bin/ccmd \
	vendor/lge/ph2n/proprietary/bin/cnd:system/bin/cnd \
	vendor/lge/ph2n/proprietary/bin/cnss-daemon:system/bin/cnss-daemon \
	vendor/lge/ph2n/proprietary/bin/cnss_diag:system/bin/cnss_diag \
	vendor/lge/ph2n/proprietary/bin/dpmd:system/bin/dpmd \
	vendor/lge/ph2n/proprietary/bin/dsqn:system/bin/dsqn \
	vendor/lge/ph2n/proprietary/bin/dsqn:system/bin/dsqn \
	vendor/lge/ph2n/proprietary/bin/dun-server:system/bin/dun-server \
	vendor/lge/ph2n/proprietary/bin/ecryptfs-run:system/bin/ecryptfs-run \
	vendor/lge/ph2n/proprietary/bin/frstd:system/bin/frstd \
	vendor/lge/ph2n/proprietary/bin/fstman:system/bin/fstman \
	vendor/lge/ph2n/proprietary/bin/ftm_ptt:system/bin/ftm_ptt \
	vendor/lge/ph2n/proprietary/bin/gbmd:system/bin/gbmd \
	vendor/lge/ph2n/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	vendor/lge/ph2n/proprietary/bin/hvdcp_opti:system/bin/hvdcp_opti \
	vendor/lge/ph2n/proprietary/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
	vendor/lge/ph2n/proprietary/bin/imscmservice:system/bin/imscmservice \
	vendor/lge/ph2n/proprietary/bin/imsdatadaemon:system/bin/imsdatadaemon \
	vendor/lge/ph2n/proprietary/bin/imsqmidaemon:system/bin/imsqmidaemon \
	vendor/lge/ph2n/proprietary/bin/irsc_util:system/bin/irsc_util \
	vendor/lge/ph2n/proprietary/bin/latd:system/bin/latd \
	vendor/lge/ph2n/proprietary/bin/loc_launcher:system/bin/loc_launcher \
	vendor/lge/ph2n/proprietary/bin/lowi-server:system/bin/lowi-server \
	vendor/lge/ph2n/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
	vendor/lge/ph2n/proprietary/bin/mcDriverDaemon_static:system/bin/mcDriverDaemon_static \
	vendor/lge/ph2n/proprietary/bin/n_smux:system/bin/n_smux \
	vendor/lge/ph2n/proprietary/bin/nl_listener:system/bin/nl_listener \
	vendor/lge/ph2n/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/lge/ph2n/proprietary/bin/pm-service:system/bin/pm-service \
	vendor/lge/ph2n/proprietary/bin/pm-proxy:system/bin/pm-proxy \
	vendor/lge/ph2n/proprietary/bin/prmd:system/bin/prmd \
	vendor/lge/ph2n/proprietary/bin/port-bridge:system/bin/port-bridge \
	vendor/lge/ph2n/proprietary/bin/ptt_socket_app:system/bin/ptt_socket_app \
	vendor/lge/ph2n/proprietary/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
	vendor/lge/ph2n/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/lge/ph2n/proprietary/bin/qseecomd:system/bin/qseecomd \
	vendor/lge/ph2n/proprietary/bin/quickdump.sh:system/bin/quickdump.sh \
	vendor/lge/ph2n/proprietary/bin/radish:system/bin/radish \
	vendor/lge/ph2n/proprietary/bin/rild:system/bin/rild \
	vendor/lge/ph2n/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/lge/ph2n/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
	vendor/lge/ph2n/proprietary/bin/shutdownanimation:system/bin/shutdownanimation \
	vendor/lge/ph2n/proprietary/bin/smpl_count:system/bin/smpl_count \
	vendor/lge/ph2n/proprietary/bin/ssr_diag:system/bin/ssr_diag \
	vendor/lge/ph2n/proprietary/bin/ssr_setup:system/bin/ssr_setup \
	vendor/lge/ph2n/proprietary/bin/tftp_server:system/bin/tftp_server \
	vendor/lge/ph2n/proprietary/bin/time_daemon:system/bin/time_daemon \
	vendor/lge/ph2n/proprietary/bin/tsdaemon:system/bin/tsdaemon \
	vendor/lge/ph2n/proprietary/bin/vpnclientd:system/bin/vpnclientd \
	vendor/lge/ph2n/proprietary/bin/wdsdaemon:system/bin/wdsdaemon \
	vendor/lge/ph2n/proprietary/bin/wififtmd:system/bin/wififtmd \
	vendor/lge/ph2n/proprietary/bin/xtwifi-client:system/bin/xtwifi-client \
	vendor/lge/ph2n/proprietary/bin/xtwifi-inet-agent:system/bin/xtwifi-inet-agent

# Crucialsoft Fingerprint
PRODUCT_COPY_FILES += \
 	vendor/lge/ph2n/proprietary/bin/fidod:system/bin/fidod \
 	vendor/lge/ph2n/proprietary/bin/fingerprintd:system/bin/fingerprintd \
	vendor/lge/ph2n/proprietary/vendor/bin/hbtp_daemon:system/vendor/bin/hbtp_daemon \
	vendor/lge/ph2n/proprietary/vendor/bin/touch_fusion:system/vendor/bin/touch_fusion \
	vendor/lge/ph2n/proprietary/lib/libfidoservice_binder.so:system/lib/libfidoservice_binder.so \
	vendor/lge/ph2n/proprietary/lib/libfpfactory_jni.so:system/lib/libfpfactory_jni.so \
	vendor/lge/ph2n/proprietary/lib/libfpfactory.so:system/lib/libfpfactory.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libhbtpclient.so:system/vendor/lib/libhbtpclient.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libhbtpdsp.so:system/vendor/lib/libhbtpdsp.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libhbtpfrmwk.so:system/vendor/lib/libhbtpfrmwk.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libhbtptouchmgrjni.so:system/vendor/lib/libhbtptouchmgrjni.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libFidoCryptoJNI.so:system/vendor/lib/libFidoCryptoJNI.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libFidoCrypto.so:system/vendor/lib/libFidoCrypto.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libFIDOKeyProvisioning.so:system/vendor/lib/libFIDOKeyProvisioning.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libFidoSuiJNI.so:system/vendor/lib/libFidoSuiJNI.so \
	vendor/lge/ph2n/proprietary/etc/firmware/qtc800s.bin:system/etc/firmware/qtc800s.bin \
	vendor/lge/ph2n/proprietary/etc/firmware/qtc800s.cfg:system/etc/firmware/qtc800s.cfg \
	vendor/lge/ph2n/proprietary/etc/firmware/hbtp/hbtpcfg_8917.dat:system/etc/firmware/hbtp/hbtpcfg_8917.dat \
	vendor/lge/ph2n/proprietary/etc/firmware/hbtp/hbtpcfg.dat:system/etc/firmware/hbtp/hbtpcfg.dat \
	vendor/lge/ph2n/proprietary/etc/firmware/hbtp/qtc800s_dsp.bin:system/etc/firmware/hbtp/qtc800s_dsp.bin

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/vendor/bin/audioflacapp:system/vendor/bin/audioflacapp \
	vendor/lge/ph2n/proprietary/vendor/bin/chamomile_provision:system/vendor/bin/chamomile_provision \
	vendor/lge/ph2n/proprietary/vendor/bin/qseeproxydaemon:system/vendor/bin/qseeproxydaemon \
	vendor/lge/ph2n/proprietary/vendor/bin/qseeproxysampledaemon:system/vendor/bin/qseeproxysampledaemon \
	vendor/lge/ph2n/proprietary/vendor/bin/qti:system/vendor/bin/qti \
	vendor/lge/ph2n/proprietary/vendor/bin/slim_daemon:system/vendor/bin/slim_daemon \
	vendor/lge/ph2n/proprietary/vendor/bin/thermal-engine:system/vendor/bin/thermal-engine

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libacdbmapper.so:system/vendor/lib/libacdbmapper.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
	vendor/lge/ph2n/proprietary/etc/acdbdata/Bluetooth_cal.acdb:system/etc/acdbdata/Bluetooth_cal.acdb \
	vendor/lge/ph2n/proprietary/etc/acdbdata/General_cal.acdb:system/etc/acdbdata/General_cal.acdb \
	vendor/lge/ph2n/proprietary/etc/acdbdata/Global_cal.acdb:system/etc/acdbdata/Global_cal.acdb \
	vendor/lge/ph2n/proprietary/etc/acdbdata/Handset_cal.acdb:system/etc/acdbdata/Handset_cal.acdb \
	vendor/lge/ph2n/proprietary/etc/acdbdata/Hdmi_cal.acdb:system/etc/acdbdata/Hdmi_cal.acdb \
	vendor/lge/ph2n/proprietary/etc/acdbdata/Headset_cal.acdb:system/etc/acdbdata/Headset_cal.acdb \
	vendor/lge/ph2n/proprietary/etc/acdbdata/Speaker_cal.acdb:system/etc/acdbdata/Speaker_cal.acdb \
	vendor/lge/ph2n/proprietary/etc/acdbdata/workspaceFile.qwsp:system/etc/acdbdata/workspaceFile.qwsp

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a330_pfp.fw:system/etc/firmware/a330_pfp.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a330_pm4.fw:system/etc/firmware/a330_pm4.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a420_pfp.fw:system/etc/firmware/a420_pfp.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a420_pm4.fw:system/etc/firmware/a420_pm4.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a530_gpmu.fw2:system/etc/firmware/a530_gpmu.fw2 \
	vendor/lge/ph2n/proprietary/etc/firmware/a530_pfp.fw:system/etc/firmware/a530_pfp.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a530_pm4.fw:system/etc/firmware/a530_pm4.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a530v1_pfp.fw:system/etc/firmware/a530v1_pfp.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a530v1_pm4.fw:system/etc/firmware/a530v1_pm4.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/a530v2_seq.fw2:system/etc/firmware/a530v2_seq.fw2 \
	vendor/lge/ph2n/proprietary/etc/firmware/a530v3_gpmu.fw2:system/etc/firmware/a530v3_gpmu.fw2 \
	vendor/lge/ph2n/proprietary/etc/firmware/a530v3_seq.fw2:system/etc/firmware/a530v3_seq.fw2 \
	vendor/lge/ph2n/proprietary/etc/firmware/a540_gpmu.fw2:system/etc/firmware/a540_gpmu.fw2 \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:system/etc/firmware/cpp_firmware_v1_10_0.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_5_0.fw:system/etc/firmware/cpp_firmware_v1_5_0.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_5_2.fw:system/etc/firmware/cpp_firmware_v1_5_2.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_6_0.fw:system/etc/firmware/cpp_firmware_v1_6_0.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_8_0.fw:system/etc/firmware/cpp_firmware_v1_8_0.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_10_0.fw:system/etc/firmware/cpp_firmware_v1_10_0.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/cpp_firmware_v1_12_0.fw:system/etc/firmware/cpp_firmware_v1_12_0.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/DE.o.msm8937:system/etc/firmware/DE.o.msm8937 \
	vendor/lge/ph2n/proprietary/etc/firmware/nvm_tlv_1.3.bin:system/etc/firmware/nvm_tlv_1.3.bin \
	vendor/lge/ph2n/proprietary/etc/firmware/nvm_tlv_2.1.bin:system/etc/firmware/nvm_tlv_2.1.bin \
	vendor/lge/ph2n/proprietary/etc/firmware/nvm_tlv_3.0.bin:system/etc/firmware/nvm_tlv_3.0.bin \
	vendor/lge/ph2n/proprietary/etc/firmware/nvm_tlv_3.2.bin:system/etc/firmware/nvm_tlv_3.2.bin \
	vendor/lge/ph2n/proprietary/etc/firmware/nvm_tlv.bin:system/etc/firmware/nvm_tlv.bin \
	vendor/lge/ph2n/proprietary/etc/firmware/ice40.bin:system/etc/firmware/ice40.bin \
	vendor/lge/ph2n/proprietary/etc/firmware/rampatch_tlv_1.3.tlv:system/etc/firmware/rampatch_tlv_1.3.tlv \
	vendor/lge/ph2n/proprietary/etc/firmware/rampatch_tlv_2.1.tlv:system/etc/firmware/rampatch_tlv_2.1.tlv \
	vendor/lge/ph2n/proprietary/etc/firmware/rampatch_tlv_3.0.tlv:system/etc/firmware/rampatch_tlv_3.0.tlv \
	vendor/lge/ph2n/proprietary/etc/firmware/rampatch_tlv_3.2.tlv:system/etc/firmware/rampatch_tlv_3.2.tlv \
	vendor/lge/ph2n/proprietary/etc/firmware/rampatch_tlv.img:system/etc/firmware/rampatch_tlv.img \
	vendor/lge/ph2n/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
	vendor/lge/ph2n/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/lib/ssl/engines/libkeystore.so:system/vendor/lib/ssl/engines/libkeystore.so

# Sound
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
	vendor/lge/ph2n/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
	vendor/lge/ph2n/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so


	#vendor/lge/ph2n/proprietary/lib/hw/sensors.msm8937.so:system/lib/hw/sensors.msm8937.so \

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/lib/hw/lgkm.default.so:system/lib/hw/lgkm.default.so \
	vendor/lge/ph2n/proprietary/lib/hw/wbc_hal.default.so:system/lib/hw/wbc_hal.default.so \
	vendor/lge/ph2n/proprietary/vendor/lib/hw/activity_recognition.msm8937.so:system/vendor/lib/hw/activity_recognition.msm8937.so \
	vendor/lge/ph2n/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
	vendor/lge/ph2n/proprietary/vendor/lib/hw/gatekeeper.msm8937.so:system/vendor/lib/hw/gatekeeper.msm8937.so \
	vendor/lge/ph2n/proprietary/vendor/lib/hw/keystore.msm8937.so:system/vendor/lib/hw/keystore.msm8937.so

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
	vendor/lge/ph2n/proprietary/lib/libHDR.so:system/lib/libHDR.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libq3dtools_esx.so:system/vendor/lib/egl/libq3dtools_esx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
	vendor/lge/ph2n/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \


PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so:system/lib/libaptX-1.0.0-rel-Android21-ARMv7A.so \
	vendor/lge/ph2n/proprietary/lib/libaptXScheduler.so:system/lib/libaptXScheduler.so

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/lib/liballegro.so:system/lib/liballegro.so \
	vendor/lge/ph2n/proprietary/lib/libatd_common.so:system/lib/libatd_common.so \
	vendor/lge/ph2n/proprietary/lib/libatd_corelib.so:system/lib/libatd_corelib.so \
	vendor/lge/ph2n/proprietary/lib/libatd_modeminterface.so:system/lib/libatd_modeminterface.so \
	vendor/lge/ph2n/proprietary/lib/libaudiohookclient.so:system/lib/libaudiohookclient.so \
	vendor/lge/ph2n/proprietary/lib/libaudiopolicymanagerqct.so:system/lib/libaudiopolicymanagerqct.so \
	vendor/lge/ph2n/proprietary/lib/libbluedroid_bdt.so:system/lib/libbluedroid_bdt.so \
	vendor/lge/ph2n/proprietary/lib/libbluetooth_jni2.so:system/lib/libbluetooth_jni2.so \
	vendor/lge/ph2n/proprietary/lib/libbluetoothsettings_jni.so:system/lib/libbluetoothsettings_jni.so \
	vendor/lge/ph2n/proprietary/lib/libbrunch.so:system/lib/libbrunch.so \
	vendor/lge/ph2n/proprietary/lib/libccm.so:system/lib/libccm.so \
	vendor/lge/ph2n/proprietary/lib/libcommonpawrapper.so:system/lib/libcommonpawrapper.so \
	vendor/lge/ph2n/proprietary/lib/libcrypto_wlan.so:system/lib/libcrypto_wlan.so \
	vendor/lge/ph2n/proprietary/lib/libdashplayer.so:system/lib/libdashplayer.so \
	vendor/lge/ph2n/proprietary/lib/libDM_Lib.so:system/lib/libDM_Lib.so \
	vendor/lge/ph2n/proprietary/lib/libdhcpcd.so:system/lib/libdhcpcd.so \
	vendor/lge/ph2n/proprietary/lib/libdsqnif.so:system/lib/libdsqnif.so \
	vendor/lge/ph2n/proprietary/lib/libDxHdcp.so:system/lib/libDxHdcp.so \
	vendor/lge/ph2n/proprietary/lib/libfotajni.so:system/lib/libfotajni.so \
	vendor/lge/ph2n/proprietary/lib/libfrst.so:system/lib/libfrst.so \
	vendor/lge/ph2n/proprietary/lib/libgba.so:system/lib/libgba.so \
	vendor/lge/ph2n/proprietary/lib/libgnsspps.so:system/lib/libgnsspps.so \
	vendor/lge/ph2n/proprietary/lib/libhwresource.so:system/lib/libhwresource.so \
	vendor/lge/ph2n/proprietary/lib/libhttppdtimedtext.so:system/lib/libhttppdtimedtext.so \
	vendor/lge/ph2n/proprietary/lib/libhashstorage_common.so:system/lib/libhashstorage_common.so \
	vendor/lge/ph2n/proprietary/lib/libhashstorage_jni.so:system/lib/libhashstorage_jni.so \
	vendor/lge/ph2n/proprietary/lib/libimsmedia.so:system/lib/libimsmedia.so \
	vendor/lge/ph2n/proprietary/lib/libicuuc_wlan.so:system/lib/libicuuc_wlan.so \
	vendor/lge/ph2n/proprietary/lib/libimsmmpf.so:system/lib/libimsmmpf.so \
	vendor/lge/ph2n/proprietary/lib/libimsrcsmedia.so:system/lib/libimsrcsmedia.so \
	vendor/lge/ph2n/proprietary/lib/libims.so:system/lib/libims.so \
	vendor/lge/ph2n/proprietary/lib/libjni_ipsecservice_lg.so:system/lib/libjni_ipsecservice_lg.so \
	vendor/lge/ph2n/proprietary/lib/libled_jni.so:system/lib/libled_jni.so \
	vendor/lge/ph2n/proprietary/lib/liblgalmond.so:system/lib/liblgalmond.so \
	vendor/lge/ph2n/proprietary/lib/liblgatcmd.so:system/lib/liblgatcmd.so \
	vendor/lge/ph2n/proprietary/lib/liblgaudioutils.so:system/lib/liblgaudioutils.so \
	vendor/lge/ph2n/proprietary/lib/liblgcamera_jni.so:system/lib/liblgcamera_jni.so \
	vendor/lge/ph2n/proprietary/lib/libLGCodecOSAL.so:system/lib/libLGCodecOSAL.so \
	vendor/lge/ph2n/proprietary/lib/libLGCodecParserUtils.so:system/lib/libLGCodecParserUtils.so \
	vendor/lge/ph2n/proprietary/lib/liblgcrypto.so:system/lib/liblgcrypto.so \
	vendor/lge/ph2n/proprietary/lib/liblgDivxDrm.so:system/lib/liblgDivxDrm.so \
	vendor/lge/ph2n/proprietary/lib/liblgdrm_adapt.so:system/lib/liblgdrm_adapt.so \
	vendor/lge/ph2n/proprietary/lib/liblgdrm_client.so:system/lib/liblgdrm_client.so \
	vendor/lge/ph2n/proprietary/lib/liblgdrm_jni.so:system/lib/liblgdrm_jni.so \
	vendor/lge/ph2n/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
	vendor/lge/ph2n/proprietary/lib/liblgvolregulator.so:system/lib/liblgvolregulator.so \
	vendor/lge/ph2n/proprietary/lib/libmtp_ex.so:system/lib/libmtp_ex.so \
	vendor/lge/ph2n/proprietary/lib/libmts.so:system/lib/libmts.so \
	vendor/lge/ph2n/proprietary/lib/liblgeaacmain.so:system/lib/liblgeaacmain.so \
	vendor/lge/ph2n/proprietary/lib/liblge_audioeffect.so:system/lib/liblge_audioeffect.so \
	vendor/lge/ph2n/proprietary/lib/liblge_divxdrm.so:system/lib/liblge_divxdrm.so \
	vendor/lge/ph2n/proprietary/lib/liblgehdcpek.so:system/lib/liblgehdcpek.so \
	vendor/lge/ph2n/proprietary/lib/liblge_servers.so:system/lib/liblge_servers.so \
	vendor/lge/ph2n/proprietary/lib/liblge_soundnormalizerV2.so:system/lib/liblge_soundnormalizerV2.so \
	vendor/lge/ph2n/proprietary/lib/liblgesourceplugin.so:system/lib/liblgesourceplugin.so \
	vendor/lge/ph2n/proprietary/lib/liblgftmitem.so:system/lib/liblgftmitem.so \
	vendor/lge/ph2n/proprietary/lib/liblghashstorage.so:system/lib/liblghashstorage.so \
	vendor/lge/ph2n/proprietary/lib/liblginvertcolor_jni.so:system/lib/liblginvertcolor_jni.so \
	vendor/lge/ph2n/proprietary/lib/liblgkm.so:system/lib/liblgkm.so \
	vendor/lge/ph2n/proprietary/lib/liblgmabl.so:system/lib/liblgmabl.so \
	vendor/lge/ph2n/proprietary/lib/liblge3dsoundengineEx.so:system/lib/liblge3dsoundengineEx.so \
	vendor/lge/ph2n/proprietary/lib/liblgetars.so:system/lib/liblgetars.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_ac3.so:system/lib/liblg_parser_ac3.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_aiff.so:system/lib/liblg_parser_aiff.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_asf.so:system/lib/liblg_parser_asf.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_avi.so:system/lib/liblg_parser_avi.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_dts.so:system/lib/liblg_parser_dts.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_flv.so:system/lib/liblg_parser_flv.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_mkv.so:system/lib/liblg_parser_mkv.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_ogm.so:system/lib/liblg_parser_ogm.so \
	vendor/lge/ph2n/proprietary/lib/libLGParserOSAL.so:system/lib/libLGParserOSAL.so \
	vendor/lge/ph2n/proprietary/lib/liblg_parser_qcp.so:system/lib/liblg_parser_qcp.so \
	vendor/lge/ph2n/proprietary/lib/liblgpca.so:system/lib/liblgpca.so \
	vendor/lge/ph2n/proprietary/lib/liblgresampler.so:system/lib/liblgresampler.so \
	vendor/lge/ph2n/proprietary/lib/liblgRmsVolComp.so:system/lib/liblgRmsVolComp.so \
	vendor/lge/ph2n/proprietary/lib/liblgruntime.so:system/lib/liblgruntime.so \
	vendor/lge/ph2n/proprietary/lib/liblgsdenc_jni.so:system/lib/liblgsdenc_jni.so \
	vendor/lge/ph2n/proprietary/lib/liblgsecclk.so:system/lib/liblgsecclk.so \
	vendor/lge/ph2n/proprietary/lib/liblgssl.so:system/lib/liblgssl.so \
	vendor/lge/ph2n/proprietary/lib/libLGTimedText_ccparser.so:system/lib/libLGTimedText_ccparser.so \
	vendor/lge/ph2n/proprietary/lib/libLGTimedText_xsub.so:system/lib/libLGTimedText_xsub.so \
	vendor/lge/ph2n/proprietary/lib/liblgupnp.so:system/lib/liblgupnp.so \
	vendor/lge/ph2n/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
	vendor/lge/ph2n/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
	vendor/lge/ph2n/proprietary/lib/libn2pm.so:system/lib/libn2pm.so \
	vendor/lge/ph2n/proprietary/lib/libOmxVpp.so:system/lib/libOmxVpp.so \
	vendor/lge/ph2n/proprietary/lib/libpdmapper.so:system/lib/libpdmapper.so \
	vendor/lge/ph2n/proprietary/lib/libpmext.so:system/lib/libpmext.so \
	vendor/lge/ph2n/proprietary/lib/libproxyhal.so:system/lib/libproxyhal.so \
	vendor/lge/ph2n/proprietary/lib/libq3d.so:system/lib/libq3d.so \
	vendor/lge/ph2n/proprietary/lib/libqomx_core.so:system/lib/libqomx_core.so \
	vendor/lge/ph2n/proprietary/lib/libqti-iop.so:system/lib/libqti-iop.so \
	vendor/lge/ph2n/proprietary/lib/libqti_performance.so:system/lib/libqti_performance.so \
	vendor/lge/ph2n/proprietary/lib/libsafezone-sw-fips-1.1.so:system/lib/1.so \
	vendor/lge/ph2n/proprietary/lib/libsoftap.so:system/lib/libsoftap.so \
	vendor/lge/ph2n/proprietary/lib/libstagefright_soft_g726dec.so:system/lib/libstagefright_soft_g726dec.so \
	vendor/lge/ph2n/proprietary/lib/libstagefright_soft_lgflacdec.so:system/lib/libstagefright_soft_lgflacdec.so \
	vendor/lge/ph2n/proprietary/lib/libstagefright_soft_lgalacdec.so:system/lib/libstagefright_soft_lgalacdec.so \
	vendor/lge/ph2n/proprietary/lib/libstagefright_soft_mjpgdec.so:system/lib/libstagefright_soft_mjpgdec.so \
	vendor/lge/ph2n/proprietary/lib/libstagefright_soft_pcmdec.so:system/lib/libstagefright_soft_pcmdec.so \
	vendor/lge/ph2n/proprietary/lib/libstagefright_soft_theoradec.so:system/lib/libstagefright_soft_theoradec.so \
	vendor/lge/ph2n/proprietary/lib/libstagefright_soft_wmadec3.so:system/lib/libstagefright_soft_wmadec3.so \
	vendor/lge/ph2n/proprietary/lib/libTBaseProvisioning.so:system/lib/libTBaseProvisioning.so \
	vendor/lge/ph2n/proprietary/lib/libtimescale_filter.so:system/lib/libtimescale_filter.so \
	vendor/lge/ph2n/proprietary/lib/libuicc.so:system/lib/libuicc.so \
	vendor/lge/ph2n/proprietary/lib/libusim_aka.so:/system/lib/libusim_aka.so \
	vendor/lge/ph2n/proprietary/lib/libVDBase.so:system/lib/libVDBase.so \
	vendor/lge/ph2n/proprietary/lib/libVDLowLightAPI.so:system/lib/libVDLowLightAPI.so \
	vendor/lge/ph2n/proprietary/lib/libvolumevibratorcallback.so:system/lib/libvolumevibratorcallback.so \
	vendor/lge/ph2n/proprietary/lib/libvolumevibrator_jni.so:system/lib/libvolumevibrator_jni.so \
	vendor/lge/ph2n/proprietary/lib/libvpplibrary.so:system/lib/libvpplibrary.so \
	vendor/lge/ph2n/proprietary/lib/libvss_bsp_qcci.so:system/lib/libvss_bsp_qcci.so \
	vendor/lge/ph2n/proprietary/lib/libvss_common_core.so:system/lib/libvss_common_core.so \
	vendor/lge/ph2n/proprietary/lib/libvss_common_idl.so:system/lib/libvss_common_idl.so \
	vendor/lge/ph2n/proprietary/lib/libvss_common_iface.so:system/lib/libvss_common_iface.so \
	vendor/lge/ph2n/proprietary/lib/libvss_dmi_qcci.so:system/lib/libvss_dmi_qcci.so \
	vendor/lge/ph2n/proprietary/lib/libvss_gnss_qcci.so:system/lib/libvss_gnss_qcci.so \
	vendor/lge/ph2n/proprietary/lib/libvss_ims_qcci.so:system/lib/libvss_ims_qcci.so \
	vendor/lge/ph2n/proprietary/lib/libvss_nv_core.so:system/lib/libvss_nv_core.so \
	vendor/lge/ph2n/proprietary/lib/libvss_nv_idl.so:system/lib/libvss_nv_idl.so \
	vendor/lge/ph2n/proprietary/lib/libvss_nv_iface.so:system/lib/libvss_nv_iface.so \
	vendor/lge/ph2n/proprietary/lib/libvss_resim_core.so:system/lib/libvss_resim_core.so \
	vendor/lge/ph2n/proprietary/lib/libvss_resim_idl.so:system/lib/libvss_resim_idl.so \
	vendor/lge/ph2n/proprietary/lib/libvss_resim_iface.so:system/lib/libvss_resim_iface.so \
	vendor/lge/ph2n/proprietary/lib/libvss_sar_qcci.so:system/lib/libvss_sar_qcci.so \
	vendor/lge/ph2n/proprietary/lib/libwbc_jni.so:system/lib/libwbc_jni.so \
	vendor/lge/ph2n/proprietary/lib/libwcnftm.so:system/lib/libwcnftm.so \
	vendor/lge/ph2n/proprietary/lib/libwfcu.so:system/lib/libwfcu.so \
	vendor/lge/ph2n/proprietary/lib/libwfd_remoteif.so:system/lib/libwfd_remoteif.so \
	vendor/lge/ph2n/proprietary/lib/libwifilgeext_jni.so:system/lib/libwifilgeext_jni.so \
	vendor/lge/ph2n/proprietary/lib/libwifilgehidden_jni.so:system/lib/libwifilgehidden_jni.so \
	vendor/lge/ph2n/proprietary/lib/libwifip2pext_jni.so:system/lib/libwifip2pext_jni.so \
	vendor/lge/ph2n/proprietary/lib/libwifip2p.so:system/lib/proprietary/lib/libwifip2p.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libadm.so:system/vendor/lib/libadm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libadpcmdec.so:system/vendor/lib/libadpcmdec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libadsp_default_listener.so:system/vendor/lib/libadsp_default_listener.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libasn1cper.so:system/vendor/lib/libasn1cper.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libasn1crt.so:system/vendor/lib/libasn1crt.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libasn1crtx.so:system/vendor/lib/libasn1crtx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libaudiodevarb.so:system/vendor/lib/libaudiodevarb.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libaudioparsers.so:system/vendor/lib/libaudioparsers.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libavenhancements.so:system/vendor/lib/libavenhancements.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libc2d30-a4xx.so:system/vendor/lib/libc2d30-a4xx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libc2d30-a5xx.so:system/vendor/lib/libc2d30-a5xx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libc2d30_bltlib.so:system/vendor/lib/libc2d30_bltlib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libChamomilePA.so:system/vendor/lib/libChamomilePA.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libchromaflash.so:system/vendor/lib/libchromaflash.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libcneconn.so:system/vendor/lib/libcneconn.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libcneqmiutils.so:system/vendor/lib/libcneqmiutils.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libcne.so:system/vendor/lib/libcne.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libCommandSvc.so:system/vendor/lib/libCommandSvc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libcppf.so:system/vendor/lib/libcppf.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdataitems.so:system/vendor/lib/libdataitems.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libDivxDrm.so:system/vendor/lib/libDivxDrm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdpmctmgr.so:system/vendor/lib/libdpmctmgr.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdpmfdmgr.so:system/vendor/lib/libdpmfdmgr.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdpmframework.so:system/vendor/lib/libdpmframework.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdpmnsrm.so:system/vendor/lib/libdpmnsrm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdpmtcm.so:system/vendor/lib/libdpmtcm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdrc.so:system/vendor/lib/libdrc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libextendedremotedisplay.so:system/vendor/lib/libextendedremotedisplay.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libfastcvadsp_stub.so:system/vendor/lib/libfastcvadsp_stub.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libfastrpc_utf_stub.so:system/vendor/lib/libfastrpc_utf_stub.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libFileMux.so:system/vendor/lib/libFileMux.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libflash_pmic.so:system/vendor/lib/libflash_pmic.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libgdtap.so:system/vendor/lib/libgdtap.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libGPreqcancel.so:system/vendor/lib/libGPreqcancel.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libGPreqcancel_svc.so:system/vendor/lib/libGPreqcancel_svc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libGPTEE.so:system/vendor/lib/libGPTEE.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libImageCorrectionWrapper.so:system/vendor/lib/libImageCorrectionWrapper.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libizat_client_api.so:system/vendor/lib/libizat_client_api.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libjpegdmahw.so:system/vendor/lib/libjpegdmahw.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblistenjni.so:system/vendor/lib/liblistenjni.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblistensoundmodel2.so:system/vendor/lib/liblistensoundmodel2.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblocationservice_glue.so:system/vendor/lib/liblocationservice_glue.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libloc_ext.so:system/vendor/lib/libloc_ext.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libloc_xtra.so:system/vendor/lib/libloc_xtra.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblowi_client.so:system/vendor/lib/liblowi_client.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblowi_wifihal_nl.so:system/vendor/lib/liblowi_wifihal_nl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblowi_wifihal.so:system/vendor/lib/liblowi_wifihal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liblqe.so:system/vendor/lib/liblqe.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmdsprpc.so:system/vendor/lib/libmdsprpc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmm-dspp-utils.so:system/vendor/lib/libmm-dspp-utils.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmm-hdcpmgr.so:system/vendor/lib/libmm-hdcpmgr.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmhttpstack.so:system/vendor/lib/libmmhttpstack.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmiipstreammmihttp.so:system/vendor/lib/libmmiipstreammmihttp.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmipstreamaal.so:system/vendor/lib/libmmipstreamaal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmipstreamnetwork.so:system/vendor/lib/libmmipstreamnetwork.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmipstreamsourcehttp.so:system/vendor/lib/libmmipstreamsourcehttp.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmipstreamutils.so:system/vendor/lib/libmmipstreamutils.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmparser_lite.so:system/vendor/lib/libmmparser_lite.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmm-qdcm-diag.so:system/vendor/lib/libmm-qdcm-diag.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmqjpegdma.so:system/vendor/lib/libmmqjpegdma.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmQSM.so:system/vendor/lib/libmmQSM.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmrtpdecoder.so:system/vendor/lib/libmmrtpdecoder.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmrtpencoder.so:system/vendor/lib/libmmrtpencoder.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmsw_detail_enhancement.so:system/vendor/lib/libmmsw_detail_enhancement.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmsw_math.so:system/vendor/lib/libmmsw_math.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmsw_opencl.so:system/vendor/lib/libmmsw_opencl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmsw_platform.so:system/vendor/lib/libmmsw_platform.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmwfdinterface.so:system/vendor/lib/libmmwfdinterface.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmwfdsinkinterface.so:system/vendor/lib/libmmwfdsinkinterface.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmwfdsrcinterface.so:system/vendor/lib/libmmwfdsrcinterface.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxAlacDec.so:system/vendor/lib/libOmxAlacDec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxAlacDecSw.so:system/vendor/lib/libOmxAlacDecSw.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxAmrwbplusDec.so:system/vendor/lib/libOmxAmrwbplusDec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxApeDec.so:system/vendor/lib/libOmxApeDec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxApeDecSw.so:system/vendor/lib/libOmxApeDecSw.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxMux.so:system/vendor/lib/libOmxMux.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxVideoDSMode.so:system/vendor/lib/libOmxVideoDSMode.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOmxWmaDec.so:system/vendor/lib/libOmxWmaDec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
	vendor/lge/ph2n/proprietary/vendor/lib/liboptizoom.so:system/vendor/lib/liboptizoom.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqcmaputils.so:system/vendor/lib/libqcmaputils.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqisl.so:system/vendor/lib/libqisl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
#	vendor/lge/ph2n/proprietary/lib/librilqmiservices.so:system/lib/librilqmiservices.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsnappy.so:system/vendor/lib/libsnappy.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libssl_wlan.so:system/vendor/lib/libssl_wlan.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmi_client_helper.so:system/vendor/lib/libqmi_client_helper.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmiservices_ext.so:system/vendor/lib/libqmiservices_ext.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqmi_wms_client_helper.so:system/vendor/lib/libqmi_wms_client_helper.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqomx_jpegdec.so:system/vendor/lib/libqomx_jpegdec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqomx_jpegenc_pipe.so:system/vendor/lib/libqomx_jpegenc_pipe.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqti-at.so:system/vendor/lib/libqti-at.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqti-gt.so:system/vendor/lib/libqti-gt.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqti-iop-client.so:system/vendor/lib/libqti-iop-client.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libQtiTether.so:system/vendor/lib/libQtiTether.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libqti-wl.so:system/vendor/lib/libqti-wl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libquipc_os_api.so:system/vendor/lib/libquipc_os_api.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libril-qc-qmi-1.so:system/vendor/lib/libril-qc-qmi-1.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libril-qc-radioconfig.so:system/vendor/lib/libril-qc-radioconfig.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
	vendor/lge/ph2n/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libSampleAuthJNI.so:system/vendor/lib/libSampleAuthJNI.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libSampleExtAuthJNI.so:system/vendor/lib/libSampleExtAuthJNI.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsc-a2xx.so:system/vendor/lib/libsc-a2xx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libscalar.so:system/vendor/lib/libscalar.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libscve_mv.so:system/vendor/lib/libscve_mv.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libscve.so:system/vendor/lib/libscve.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libscve_stub.so:system/vendor/lib/libscve_stub.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libscveTextRecoPostProcessing.so:system/vendor/lib/libscveTextRecoPostProcessing.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsdm-color.so:system/vendor/lib/libsdm-color.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsdm-diag.so:system/vendor/lib/libsdm-diag.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsdm-disp-apis.so:system/vendor/lib/libsdm-disp-apis.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsdmextension.so:system/vendor/lib/libsdmextension.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libSecureExtAuthJNI.so:system/vendor/lib/libSecureExtAuthJNI.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libSecureSampleAuthJNI.so:system/vendor/lib/libSecureSampleAuthJNI.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libSecureUILib.so:system/vendor/lib/libSecureUILib.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsecureui.so:system/vendor/lib/libsecureui.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsecureuisvc_jni.so:system/vendor/lib/libsecureuisvc_jni.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsecureui_svcsock.so:system/vendor/lib/libsecureui_svcsock.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libseemore.so:system/vendor/lib/libseemore.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsensor_lge_cal.so:system/vendor/lib/libsensor_lge_cal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsensor_test.so:system/vendor/lib/libsensor_test.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsensor_thresh.so:system/vendor/lib/libsensor_thresh.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsensor_user_cal.so:system/vendor/lib/libsensor_user_cal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libslimclient.so:system/vendor/lib/libslimclient.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsmemlog.so:system/vendor/lib/libsmemlog.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsmwrapper.so:system/vendor/lib/libsmwrapper.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsrsprocessing.so:system/vendor/lib/libsrsprocessing.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libStDrvInt.so:system/vendor/lib/libStDrvInt.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsubsystem_control.so:system/vendor/lib/libsubsystem_control.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libSubSystemShutdown.so:system/vendor/lib/libSubSystemShutdown.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsurround_3mic_proc.so:system/vendor/lib/libsurround_3mic_proc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libswvdec.so:system/vendor/lib/libswvdec.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libsystem_health_mon.so:system/vendor/lib/libsystem_health_mon.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libtm_interface.so:system/vendor/lib/libtm_interface.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libtrueportrait.so:system/vendor/lib/libtrueportrait.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libts_detected_face_hal.so:system/vendor/lib/libts_detected_face_hal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libts_face_beautify_hal.so:system/vendor/lib/libts_face_beautify_hal.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libtzdrmgenprov.so:system/vendor/lib/libtzdrmgenprov.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libubifocus.so:system/vendor/lib/libubifocus.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libvendorconn.so:system/vendor/lib/libvendorconn.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libvoice-svc.so:system/vendor/lib/libvoice-svc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libvqzip.so:system/vendor/lib/libvqzip.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdavenhancements.so:system/vendor/lib/libwfdavenhancements.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdcommonutils.so:system/vendor/lib/libwfdcommonutils.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdhdcpcp.so:system/vendor/lib/libwfdhdcpcp.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdmmservice.so:system/vendor/lib/libwfdmmservice.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdmmsink.so:system/vendor/lib/libwfdmmsink.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdmmsrc.so:system/vendor/lib/libwfdmmsrc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdmmutils.so:system/vendor/lib/libwfdmmutils.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdnative.so:system/vendor/lib/libwfdnative.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdrtsp.so:system/vendor/lib/libwfdrtsp.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdservice.so:system/vendor/lib/libwfdservice.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfdsm.so:system/vendor/lib/libwfdsm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfduibcinterface.so:system/vendor/lib/libwfduibcinterface.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfduibcsinkinterface.so:system/vendor/lib/libwfduibcsinkinterface.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfduibcsink.so:system/vendor/lib/libwfduibcsink.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfduibcsrcinterface.so:system/vendor/lib/libwfduibcsrcinterface.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwfduibcsrc.so:system/vendor/lib/libwfduibcsrc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwms.so:system/vendor/lib/libwms.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libwqe.so:system/vendor/lib/libwqe.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libxtadapter.so:system/vendor/lib/libxtadapter.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libxt_native.so:system/vendor/lib/libxt_native.so \
	vendor/lge/ph2n/proprietary/vendor/lib/libxtwifi_ulp_adaptor.so:system/vendor/lib/libxtwifi_ulp_adaptor.so \
	vendor/lge/ph2n/proprietary/vendor/lib/sensor_calibrate.so:system/vendor/lib/sensor_calibrate.so \
	vendor/lge/ph2n/proprietary/vendor/lib/sensors.ssc.so:system/vendor/lib/ssc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/test_suite_all_modules.so:system/vendor/lib/test_suite_all_modules.so \
	vendor/lge/ph2n/proprietary/vendor/lib/test_suite_no_sensor.so:system/vendor/lib/test_suite_no_sensor.so \
	vendor/lge/ph2n/proprietary/vendor/lib/test_suite_pproc.so:system/vendor/lib/test_suite_pproc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/test_suite_vfe.so:system/vendor/lib/test_suite_vfe.so \

# MMI but y
PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/bin/mtsd:system/bin/mtsd \
	vendor/lge/ph2n/proprietary/bin/mmi:system/bin/mmi \
	vendor/lge/ph2n/proprietary/bin/mmi_agent32:system/bin/mmi_agent32 \
	vendor/lge/ph2n/proprietary/bin/mmi_debug:system/bin/mmi_debug \
	vendor/lge/ph2n/proprietary/bin/mmi_diag:system/bin/mmi_diag \
	vendor/lge/ph2n/proprietary/bin/wififtmd:system/bin/wififtmd \
	vendor/lge/ph2n/proprietary/vendor/lib/libmmi.so:system/vendor/lib/libmmi.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_audio.so:system/vendor/lib/mmi_audio.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_battery.so:system/vendor/lib/mmi_battery.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_bluetooth.so:system/vendor/lib/mmi_bluetooth.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_camera.so:system/vendor/lib/mmi_camera.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_cpu.so:system/vendor/lib/mmi_cpu.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_flashlight.so:system/vendor/lib/mmi_flashlight.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_fm.so:system/vendor/lib/mmi_fm.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_gps.so:system/vendor/lib/mmi_gps.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_headset.so:system/vendor/lib/mmi_headset.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_key.so:system/vendor/lib/mmi_key.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_lcd.so:system/vendor/lib/mmi_lcd.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_light.so:system/vendor/lib/mmi_light.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_memory.so:system/vendor/lib/mmi_memory.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_nfc.so:system/vendor/lib/mmi_nfc.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_sensor.so:system/vendor/lib/mmi_sensor.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_sim.so:system/vendor/lib/mmi_sim.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_storage.so:system/vendor/lib/mmi_storage.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_sysinfo.so:system/vendor/lib/mmi_sysinfo.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_touch.so:system/vendor/lib/mmi_touch.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_vibrator.so:system/vendor/lib/mmi_vibrator.so \
	vendor/lge/ph2n/proprietary/vendor/lib/mmi_wifi.so:system/vendor/lib/mmi_wifi.so \
