# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/ph2n/setup-makefiles.sh

$(call inherit-product, vendor/lge/ph2n/ph2n-vendor-blobs.mk)

# LG
PRODUCT_PACKAGES += \
	libjpeg_turbo

# system/app
PRODUCT_PACKAGES += \
	atfwd \
	btmultisim \
	com.quicinc.wbcserviceapp \
	FidoASM \
	FidoAuthenticator \
	FidoClient \
	FidoCryptoService \
	FidoSuiService \
	IPsecService_LG \
	IPService \
	LGATCMDService \
	LGDrm \
	QtiTelephonyService \
	SecureExtAuthService \
	SecureSampleAuthService \
	shutdownlistener \
	TimeService \
	WfdService \
	WifiCall \
	xdivert

# system/priv-app
PRODUCT_PACKAGES += \
	CNEService \
	com.qualcomm.location \
	dpmserviceapp \
	Ims4 \
	qcrilmsgtunnel \
	QtiTetherService \
	RCSProvider \
	TelephonyExtVodafonePack \
	TMO_MyAccount \
	TMO_Simlock \
	VpnClient_LG \
	xtra_t_app

# system/framework
PRODUCT_PACKAGES += \
	btmultisimlibrary \
	cneapiclient \
	com.ipsec.client \
	com.lge.ims.rcs.media \
	com.lge.wfds.send \
	com.qti.dpmframework \
	com.qti.location.sdk \
	com.qti.snapdragon.sdk.display \
	com.quicinc.cne \
	com.quicinc.wbc \
	com.quicinc.wbcservice \
	dpmapi \
	dpm \
	embmslibrary \
	imscmlibrary \
	ims-common \
	org.codeaurora.camera \
	qcnvitems \
	qcrilhook \
	qmapbridge \
	QPerformance \
	qti-telephony-common \
	QtiTelephonyServicelibrary \
	qti-vzw-ims-internal \
	rcsimssettings \
	rcs_plugin_aidl \
	rcs_service_aidl \
	rcs_service_api \
	rcsservice \
	tcmclient \
	WfdCommon

# system/vendor/app
PRODUCT_PACKAGES += \
	CABLService \
	SVIService

# system/vendor/lib
PRODUCT_PACKAGES += \
	libmdmdetect \
	libqct_resampler \
	libtime_genoff \
	libMpeg4SwEncoder \
	libNimsWrap

PRODUCT_COPY_FILES += \
	vendor/lge/ph2n/proprietary/etc/bluetooth/auto_pair_devlist.conf:system/etc/bluetooth/auto_pair_devlist.conf \
	vendor/lge/ph2n/proprietary/etc/bluetooth/avrcp_toggle_white_list.conf:system/etc/bluetooth/avrcp_toggle_white_list.conf \
	vendor/lge/ph2n/proprietary/etc/bluetooth/block_avrcp_toggle_new.conf:system/etc/bluetooth/block_avrcp_toggle_new.conf \
	vendor/lge/ph2n/proprietary/etc/bluetooth/bt_did.conf:system/etc/bluetooth/bt_did.conf \
	vendor/lge/ph2n/proprietary/etc/bluetooth/bt_tts_list.conf:system/etc/bluetooth/bt_tts_list.conf \
	vendor/lge/ph2n/proprietary/etc/bluetooth/connect_other_profile_timeout_list.conf:system/etc/bluetooth/connect_other_profile_timeout_list.conf \
	vendor/lge/ph2n/proprietary/etc/bluetooth/feature_config.xml:system/etc/bluetooth/feature_config.xml \
	
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/ramoops_backup.sh:system/etc/ramoops_backup.sh \
	$(LOCAL_PATH)/proprietary/etc/init.lge.gons.sh:system/etc/init.lge.gons.sh \
	$(LOCAL_PATH)/proprietary/etc/hcidump.sh:system/etc/hcidump.sh

PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/RIDL/qdss.cfg:system/etc/RIDL/qdss.cfg

PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/mts_mask/all.cfg:system/etc/mts_mask/all.cfg \
	$(LOCAL_PATH)/proprietary/etc/mts_mask/erase.cfg:system/etc/mts_mask/erase.cfg

# NFC access control + feature files + configuration
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/etc/libnfc-brcm.conf:system/etc/libnfc-brcm.conf \
    $(LOCAL_PATH)/proprietary/etc/libnfc-nxp.conf:system/etc/libnfc-nxp.conf \
    $(LOCAL_PATH)/proprietary/etc/libnfc-nxp-lg.conf:system/etc/libnfc-nxp-lg.conf

PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_AU.xml:system/etc/nfc/config_AU.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_CA.xml:system/etc/nfc/config_CA.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_CN.xml:system/etc/nfc/config_CN.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_COM.xml:system/etc/nfc/config_COM.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_CO.xml:system/etc/nfc/config_CO.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_HK.xml:system/etc/nfc/config_HK.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_IL.xml:system/etc/nfc/config_IL.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_JP.xml:system/etc/nfc/config_JP.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_KR.xml:system/etc/nfc/config_KR.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_nfcopen.xml:system/etc/nfc/config_nfcopen.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_nfc.xml:system/etc/nfc/config_nfc.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_NZ.xml:system/etc/nfc/config_NZ.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_PL.xml:system/etc/nfc/config_PL.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config_US.xml:system/etc/nfc/config_US.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/config.xml:system/etc/nfc/config.xml \
	$(LOCAL_PATH)/proprietary/etc/nfc/target_list.xml:system/etc/nfc/target_list.xml

PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/camera/camera_config.xml:system/etc/camera/camera_config.xml \
	$(LOCAL_PATH)/proprietary/etc/camera/csidtg_camera.xml:system/etc/camera/csidtg_camera.xml \
	$(LOCAL_PATH)/proprietary/etc/camera/csidtg_chromatix.xml:system/etc/camera/csidtg_chromatix.xml \
	$(LOCAL_PATH)/proprietary/etc/camera/hi553_chromatix.xml:system/etc/camera/hi553_chromatix.xml \
	$(LOCAL_PATH)/proprietary/etc/camera/mn34153_chromatix.xml:system/etc/camera/mn34153_chromatix.xml \
	$(LOCAL_PATH)/proprietary/etc/camera/msm8937_camera.xml:system/etc/camera/msm8937_camera.xml \
	$(LOCAL_PATH)/proprietary/etc/camera/ov8858_chromatix.xml:system/etc/camera/ov8858_chromatix.xml \
	$(LOCAL_PATH)/proprietary/etc/camera/s5k3l8_f3l8yam_chromatix.xml:system/etc/camera/s5k3l8_f3l8yam_chromatix.xml \
	$(LOCAL_PATH)/proprietary/etc/camera/s5k3m2xm_chromatix_bear.xml:system/etc/camera/s5k3m2xm_chromatix_bear.xml\
	$(LOCAL_PATH)/proprietary/etc/camera/s5k3p3_chromatix.xml:system/etc/camera/s5k3p3_chromatix.xml

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/etc/sensors/hals.conf:system/etc/sensors/hals.conf \
    $(LOCAL_PATH)/proprietary/etc/sensors/sensor_def_common.conf:system/etc/sensors/sensor_def_common.conf \
	$(LOCAL_PATH)/proprietary/etc/sensors/sensor_def_variable.conf:system/etc/sensors/sensor_def_variable.conf

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/etc/cacert_location.pem:system/etc/cacert_location.pem \
    $(LOCAL_PATH)/proprietary/etc/flp.conf:system/etc/flp.conf \
    $(LOCAL_PATH)/proprietary/etc/gps.conf:system/etc/gps.conf \
    $(LOCAL_PATH)/proprietary/etc/ike_conf.xml:system/etc/ike_conf.xml \
    $(LOCAL_PATH)/proprietary/etc/izat.conf:system/etc/izat.conf \
	$(LOCAL_PATH)/proprietary/etc/lowi.conf:system/etc/lowi.conf \
    $(LOCAL_PATH)/proprietary/etc/sap.conf:system/etc/sap.conf \
    $(LOCAL_PATH)/proprietary/etc/xtwifi.conf:system/etc/xtwifi.conf \
    $(LOCAL_PATH)/proprietary/etc/xtra_root_cert.pem:system/etc/xtra_root_cert.pem

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/etc/surround_sound_3mic/surround_sound_rec_5.1.cfg:system/etc/surround_sound_3mic/surround_sound_rec_5.1.cfg \
    $(LOCAL_PATH)/proprietary/etc/surround_sound_3mic/surround_sound_rec_AZ.cfg:system/etc/surround_sound_3mic/surround_sound_rec_AZ.cfg

# IPC router config
PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/etc/sec_config:system/etc/sec_config

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    $(LOCAL_PATH)/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    $(LOCAL_PATH)/proprietary/etc/media_profiles_8956.xml:system/etc/media_profiles_8956.xml

PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/DxHDCP.cfg:system/etc/DxHDCP.cfg \
	$(LOCAL_PATH)/proprietary/etc/andsf_310160.xml:system/etc/andsf_310160.xml \
	$(LOCAL_PATH)/proprietary/etc/andsf_310260.xml:system/etc/andsf_310260.xml \
	$(LOCAL_PATH)/proprietary/etc/ap.ubid:system/etc/ap.ubid \
	$(LOCAL_PATH)/proprietary/etc/audio_platform_info.xml:system/etc/audio_platform_info.xml \
	$(LOCAL_PATH)/proprietary/etc/capability.xml:system/etc/capability.xml \
	$(LOCAL_PATH)/proprietary/etc/ftm_test_config:system/etc/ftm_test_config \
	$(LOCAL_PATH)/proprietary/etc/ftm_test_config_wcd9335:system/etc/ftm_test_config_wcd9335 \
	$(LOCAL_PATH)/proprietary/etc/mapcon_conf.xml:system/etc/mapcon_conf.xml \
	$(LOCAL_PATH)/proprietary/etc/telephony.xml:system/etc/telephony.xml \
	$(LOCAL_PATH)/proprietary/etc/wfdconfig.xml:system/etc/wfdconfig.xml \
	$(LOCAL_PATH)/proprietary/etc/wfdconfigsink.xml:system/etc/wfdconfigsink.xml

# LGODM
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/lgodm/1xCSFB.cfg:system/etc/lgodm/1xCSFB.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/audio.cfg:system/etc/lgodm/audio.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/audio_voc_dump.cfg:system/etc/lgodm/audio_voc_dump.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/auto.cfg:system/etc/lgodm/auto.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/auto_pn.txt:system/etc/lgodm/auto_pn.txt \
	$(LOCAL_PATH)/proprietary/etc/lgodm/bt.cfg:system/etc/lgodm/bt.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/CSFB.cfg:system/etc/lgodm/CSFB.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/current_cfg.txt:system/etc/lgodm/current_cfg.txt \
	$(LOCAL_PATH)/proprietary/etc/lgodm/current_evt.txt:system/etc/lgodm/current_evt.txt \
	$(LOCAL_PATH)/proprietary/etc/lgodm/current_nfile.txt:system/etc/lgodm/current_nfile.txt \
	$(LOCAL_PATH)/proprietary/etc/lgodm/Data_UICC.cfg:system/etc/lgodm/Data_UICC.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/DDM.cfg:system/etc/lgodm/DDM.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/default.cfg:system/etc/lgodm/default.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/default.evt:system/etc/lgodm/default.evt \
	$(LOCAL_PATH)/proprietary/etc/lgodm/erase.cfg:system/etc/lgodm/erase.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/full.cfg:system/etc/lgodm/full.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/gps.cfg:system/etc/lgodm/gps.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/gps_sap_pdr.cfg:system/etc/lgodm/gps_sap_pdr.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/LGMOS_user:system/etc/lgodm/LGMOS_user \
	$(LOCAL_PATH)/proprietary/etc/lgodm/LGU_RP_ROAM.cfg:system/etc/lgodm/LGU_RP_ROAM.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/mex_16k_ref.wav:system/etc/lgodm/mex_16k_ref.wav \
	$(LOCAL_PATH)/proprietary/etc/lgodm/mex_8k_ref.wav:system/etc/lgodm/mex_8k_ref.wav \
	$(LOCAL_PATH)/proprietary/etc/lgodm/mex.cfg:system/etc/lgodm/mex.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/PolicymanODL.cfg:system/etc/lgodm/PolicymanODL.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/Radio_Audio.cfg:system/etc/lgodm/Radio_Audio.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/Radio_Audio_Data.cfg:system/etc/lgodm/Radio_Audio_Data.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/Radio_Data.cfg:system/etc/lgodm/Radio_Data.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/RadioProtocol.cfg:system/etc/lgodm/RadioProtocol.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/Radio_UICC.cfg:system/etc/lgodm/Radio_UICC.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/RP_SKT_KT.cfg:system/etc/lgodm/RP_SKT_KT.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/Sensor.cfg:system/etc/lgodm/Sensor.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/SGLTE.cfg:system/etc/lgodm/SGLTE.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/SingleLTE.cfg:system/etc/lgodm/SingleLTE.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/SingleLTE_vocoder_only_IPA.cfg:system/etc/lgodm/SingleLTE_vocoder_only_IPA.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/sms.cfg:system/etc/lgodm/sms.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/SVLTE.cfg:system/etc/lgodm/SVLTE.cfg \
	$(LOCAL_PATH)/proprietary/etc/lgodm/uicc.cfg:system/etc/lgodm/uicc.cfg

# MMI
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/mmi/fail.png:system/etc/mmi/fail.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/fonts.ttf:system/etc/mmi/fonts.ttf \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout:system/etc/mmi/layout \
	$(LOCAL_PATH)/proprietary/etc/mmi/mmi.cfg:system/etc/mmi/mmi.cfg \
	$(LOCAL_PATH)/proprietary/etc/mmi/mmi-pcba.cfg:system/etc/mmi/mmi-pcba.cfg \
	$(LOCAL_PATH)/proprietary/etc/mmi/pagedown.png:system/etc/mmi/pagedown.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/pageup.png:system/etc/mmi/pageup.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/pass.png:system/etc/mmi/pass.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/path_config.xml:system/etc/mmi/path_config.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/poweroff.png:system/etc/mmi/poweroff.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/qualsound.wav:system/etc/mmi/qualsound.wav \
	$(LOCAL_PATH)/proprietary/etc/mmi/reboot.png:system/etc/mmi/reboot.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/report.png:system/etc/mmi/report.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/reset.png:system/etc/mmi/reset.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/runall.png:system/etc/mmi/runall.png \
	$(LOCAL_PATH)/proprietary/etc/mmi/strings.xml:system/etc/mmi/strings.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/strings-zh-rCN.xml:system/etc/mmi/strings-zh-rCN.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/footer_fail.xml:system/etc/mmi/layout/footer_fail.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/footer.xml:system/etc/mmi/layout/footer.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/header.xml:system/etc/mmi/layout/header.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_battery.xml:system/etc/mmi/layout/layout_battery.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_bluetooth.xml:system/etc/mmi/layout/layout_bluetooth.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_button_backlight.xml:system/etc/mmi/layout/layout_button_backlight.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_camera_back.xml:system/etc/mmi/layout/layout_camera_back.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_camera_front.xml:system/etc/mmi/layout/layout_camera_front.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_cb.xml:system/etc/mmi/layout/layout_cb.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_common.xml:system/etc/mmi/layout/layout_common.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_confirm.xml:system/etc/mmi/layout/layout_confirm.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_cpu.xml:system/etc/mmi/layout/layout_cpu.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_emmc.xml:system/etc/mmi/layout/layout_emmc.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_feedback.xml:system/etc/mmi/layout/layout_feedback.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_flashlight.xml:system/etc/mmi/layout/layout_flashlight.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_fm.xml:system/etc/mmi/layout/layout_fm.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_gps.xml:system/etc/mmi/layout/layout_gps.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_gsensor.xml:system/etc/mmi/layout/layout_gsensor.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_gyroscope.xml:system/etc/mmi/layout/layout_gyroscope.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_handset.xml:system/etc/mmi/layout/layout_handset.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_headset_key.xml:system/etc/mmi/layout/layout_headset_key.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_headset.xml:system/etc/mmi/layout/layout_headset.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_key.xml:system/etc/mmi/layout/layout_key.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_lcd_backlight.xml:system/etc/mmi/layout/layout_lcd_backlight.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_lcd.xml:system/etc/mmi/layout/layout_lcd.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_led_blue.xml:system/etc/mmi/layout/layout_led_blue.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_led_green.xml:system/etc/mmi/layout/layout_led_green.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_led_red.xml:system/etc/mmi/layout/layout_led_red.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_loudspeaker.xml:system/etc/mmi/layout/layout_loudspeaker.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_lsensor.xml:system/etc/mmi/layout/layout_lsensor.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_memory.xml:system/etc/mmi/layout/layout_memory.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_msensor.xml:system/etc/mmi/layout/layout_msensor.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_nfc.xml:system/etc/mmi/layout/layout_nfc.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_pcba.xml:system/etc/mmi/layout/layout_pcba.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_primary_mic.xml:system/etc/mmi/layout/layout_primary_mic.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_psensor.xml:system/etc/mmi/layout/layout_psensor.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_reboot.xml:system/etc/mmi/layout/layout_reboot.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_report.xml:system/etc/mmi/layout/layout_report.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_sdcard.xml:system/etc/mmi/layout/layout_sdcard.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_simcard1.xml:system/etc/mmi/layout/layout_simcard1.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_simcard2.xml:system/etc/mmi/layout/layout_simcard2.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_system_info.xml:system/etc/mmi/layout/layout_system_info.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_touch.xml:system/etc/mmi/layout/layout_touch.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_vibrator.xml:system/etc/mmi/layout/layout_vibrator.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/layout_wifi.xml:system/etc/mmi/layout/layout_wifi.xml \
	$(LOCAL_PATH)/proprietary/etc/mmi/layout/main.xml:system/etc/mmi/layout/main.xml

# ETC
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/cne/andsfCne.xml:system/etc/cne/andsfCne.xml \
	$(LOCAL_PATH)/proprietary/etc/cne/SwimConfig.xml:system/etc/cne/SwimConfig.xml \
	$(LOCAL_PATH)/proprietary/etc/data/dsi_config.xml:system/etc/data/dsi_config.xml \
	$(LOCAL_PATH)/proprietary/etc/data/netmgr_config.xml:system/etc/data/netmgr_config.xml \
	$(LOCAL_PATH)/proprietary/etc/data/qmi_config.xml:system/etc/data/qmi_config.xml \
	$(LOCAL_PATH)/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
	$(LOCAL_PATH)/proprietary/etc/dpm/nsrm/NsrmConfiguration.xml:system/etc/dpm/nsrm/NsrmConfiguration.xml \
	$(LOCAL_PATH)/proprietary/etc/drc/drc_cfg_5.1.txt:system/etc/drc/drc_cfg_5.1.txt \
	$(LOCAL_PATH)/proprietary/etc/drc/drc_cfg_AZ.txt:system/etc/drc/drc_cfg_AZ.txt \
	$(LOCAL_PATH)/proprietary/etc/thermal-engine-8937.conf:system/etc/thermal-engine-8937.conf \
	$(LOCAL_PATH)/proprietary/etc/thermal-engine-default.conf:system/etc/thermal-engine-default.conf

PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/proprietary/etc/permissions/btmultisim.xml:system/etc/permissions/btmultisim.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.ipsec.client.xml:system/etc/permissions/com.ipsec.client.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.lge.ims.xml:system/etc/permissions/com.lge.ims.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.lge.ims.rcs.xml:system/etc/permissions/com.lge.ims.rcs.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.lge.ims.rcs.media.xml:system/etc/permissions/com.lge.ims.rcs.media.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.lge.lgdrm.xml:system/etc/permissions/com.lge.lgdrm.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.lge.permissions.xml:system/etc/permissions/com.lge.permissions.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.lge.wfds.xml:system/etc/permissions/com.lge.wfds.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.quicinc.wbc.xml:system/etc/permissions/com.quicinc.wbc.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/com.quicinc.wbcservice.xml:system/etc/permissions/com.quicinc.wbcservice.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/imscm.xml:system/etc/permissions/imscm.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/qcnvitems.xml:system/etc/permissions/qcnvitems.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/qti-vzw-ims-internal.xml:system/etc/permissions/qti-vzw-ims-internal.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/rcs_service_aidl.xml:system/etc/permissions/rcs_service_aidl.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/rcs_service_api.xml:system/etc/permissions/rcs_service_api.xml \
	$(LOCAL_PATH)/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml
